language: objective-c
osx_image: xcode8.3
xcode_project: FlyveMDMInventory.xcodeproj
xcode_scheme: FlyveMDMInventory
install:
- "./ci/install.sh"
before_script:
- "./ci/before_script.sh"
script:
- "./ci/script.sh"
after_success:
- "./ci/deploy.sh"
deploy:
  provider: script
  script: "./ci/push.sh"
  on:
    tags: true
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
env:
  global:
  - APPNAME="FlyveMDMInventory"
  - GH_USER=flyve-mdm-bot
  - secure: jRu+QFkub7B41u3BQWCjlD+e9hybjrKODiQ3WHrlN4dGdrIez8e5zeL9YXWnInU6qT7oDRUhKFaSTYLk8deiF4doQIUAQQMWKYnxs6bQUiaVRXjgvtvHWV0NE3g+NGIYhif7OV/YvTxFwVzA6R24bpH/TjhVSFvmpW8O7xCsWJnX3E8+KF0uUQXq6uJ49AMBpb/t98pmwuIkzKLAh22ASQi1c/OdE7yRbkb12FQh/R3OeNsHUpF9C1NQoxUFByrx6qXrKFgJEJHHrq7MRACrI3UgxagSGWW8wraEnJsCIYSXF6ZxoJzgpWsae5KNSIUWqPn1hLOqTuYvCvmYt9XvTFq/FW6UR8JC53h/Z3CodVCl2wKL7R7WuQu46Bn/5Wmd34tCheefj0V+RyrApYcesmsVV+yFP9GhXctU5qMdkboNdFt52vh9a1GFTB11oD1trmw3EFkWO/lpnz7jK7ob0D90Tmdom8yl65OR7ppFjJ+Qnf6FN8CCWFrQXGyxxB6VtS7A0mJW4jTQk6UDS3xG5C45FtxuoR++Mxo7B0Gq1N5GV7TY6XYpKcAH3YTxNp+9rw/NCg8wDalmg3TBgXIQk0AiQMfswUf8pMTnWFkYJ33J6Fggi2S1CDoIqUgNOE4rTa1/5+EEPEP2W90lM2Tr17Tn3hpzPu9IxVAuUWJn6PY=
  - secure: pTRX52ehBNlRCP3plPCJacx4fTKX1NCungrqSaYq9VJNewIwzKGxCxzNDHHZPBFqufc0oPjsN8ruq1LkR1lckew/FKqtWqZV59EwMsZ89Q1nCponEwO+1dzFg31JAp1s7xPbTTQqsMomhVL/SGUE3EilRDjsqNinkLwPG1EkEfr+mqne6Ocw9AJ9sdjjnwiH0wQQXnooMCH3wL6zyKwerX0ZFnjRhuKCn2dcodNzi5E1aelq1it4Ewjpwz05SpnK5mmVce+aAC/8NnvIMDDaNl4UTtx2sF08eIptmuja1WidSlVNbPcJYNoZsnaal8KkTGmEu6ng21pGmDPMc1sn8yM7dYV49QAWeHkSMfhjdgb9dYX2dxKG237rT0wX9bbdNBxuZDZCl/XJRs0sldOIoq9YcYFxD5KNjVdQnPDfQQWiSmtFDSxVrLK7jzrZvh04TMBgaLeeErtxTEohUYyblcAgpdN6xT38VPoCRh/iXnKl5NR+Be2TtDOEV6tGJPbHrZTU8neJibB2nV3x52OWr5dyyleL5Hc3MV9RdRGimLgVieiPHXJ9Un2GEHQ+Nb59bqWB27aCfB/grI5mQr11MWs4EvtSpoiJftajy4ADhk80ooM1oJW1uynnPdP+xrCfsstKk0HLgdcXMg046k4CFCTZux0D+OD1TgOi0r1RZNA=
  - secure: mdCYodNfgNFNaPI3aGY3KPI15iS44vFW/1Vwkkia8Sdw80JvFhtOYGt1qepQCt3CvMj8367DI9FOQHUSCR0SEtJ9cacq1zcdhYh3vSsfi8Prx+rdRLc31BKUyeAUPeUTF3DlE4vhdxVZAduJuZ079qHBWwfSB8DZeZNlXmub5fFvHNczLvYYz4C8JKnKrqRZ4KgjtrnmpTT17yDWPcawzT0ObF56RLY7rfyQwbyQIprPoKpZfNt5GUDE8rSZnx7EbY4Ugg6oH9QMXlGoonMeYflqLJEwYwsYJjbaCx+LKkxQViEmSSj/6XVdMz0StFdvnQI8h5z47K9XuvsF9lwdNWdhnvo7zhLPh+4IWENJ+udB72zvQKjp3VvNptf/Bmk3OoSuPeDQd+ovRhlTxHF8BtaPFN6SI7o0YabbU6ZVNWo6L3QSqhkgYUrmy/B+fOQyUIOo+1ETB81kPf7UwMFiOIOdRVD7Tdl/8BAdCav5HCmLv/rggeVkz9wU7ULBPzO93QEb64ct4CXdJOJKzNVEvcVcDFuvvrDGQEZXfYm4JnkA8YyklIkj73gZhKBT5I/0MgUr2HcrTP8jDz7D7cT+fzF/hwfKrQSPYjEtwLIHVA0nX+uT3mRF8Ip7ig7n8hCkwA09fQ8Xxnoj5df5UMU8iskmHEaJFa1w14wg2iWwmlQ=
  - secure: Xh4czf3g96ZUtzIUuJOnQGQ/WXfzsMmIsSSOdy5S4QGu1hkIF66Ux2OCd/Gn6GNzv8J60yBIeB7Im1TtARxS5VUZ1FKUM6fcE3ITwFsUadPNDVe5leActbIEBq67V/+0i1bGb35WtAC/4CsbRlVtY44COzjAbIkDdUmmJof4Zd8vKYSm1yW6B9cIbD3V+BOGc34h4EoYdTmYpmcGuCxTBku+Xq0Lne50zTuMlgNclW1IABmgfM22igayEP3F7ZziyqWVYsvzwSEhSiRkO5ZLbKPydGev5Qz5lnXeK0XD1IVrYM2OWzOKqoJH8DJRa130X6hEQb22+GvqEjeKrn86mgF6BAR+iqc3HoyHP6owUGmy2+vOBO2wiv3MGJsUoQ840dPZJmb0K84P0LQhQbIsh8XyCq749HilCS6b4QzHMPoZIH/ftN/d+EWEdLagn7nvGP+M5+3I7NcYQSkLLiDFGW7/mLv8SoqIjowNIaICFUcH1wKRQIWHChtnKSpfA4RecjUglyVkyxoVt7Qb4IbDmQyP3VSxdCeWnXWCUrHBaji9YtjKqgdqYDhth6/9/I5fDi282msAKNbUhHEL3He3nXTHNd+2HTfL3UK8e/S8e5QxQ6mbzg3wcbbXAPbdib2cph3TEWUBo2QkIL+6+G9oaJhSUxebsyHJkHlW/Amqy+s=
